version: '3'

services:
  app:
    build:
      context: .
      dockerfile: minotor/Dockerfile
    command: python /code/minotor/run.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '8888:8888'
    volumes:
      - ./minotor/front/build:/code/minotor/front/build
      - ./minotor:/code/minotor

  npm:
    build: minotor/front
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./minotor/front:/code
