version: '3'

services:
  app:
    build:
      context: .
      dockerfile: minotoring/Dockerfile
    command: python /code/minotoring/run.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '8888:8888'
    volumes:
      - ./minotoring/front/build:/code/minotoring/front/build
      - ./minotoring:/code/minotoring

  npm:
    build: minotoring/front
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./minotoring/front:/code
