version: "3"

services:

  app:
    build: .
    command: python run.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  npm:
    build: front
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./front:/code
