name: React Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.10.1
      - name: Installing dependencies
        run: npm install
      - name: Running jest tests
        run: npm react-scripts test
